apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: camperjames-Ushahidi
  description: The Ushahidi Web Application
  annotations:
    example.com/service-discovery: artistweb
    github.com/project-slug: github/DeepJames/Ushahidi_Web
  tags:
    - java
spec:
  type: website
  lifecycle: experimental
  owner: myteam
  system: public-websites
